keys = ['links',
    'event_promotion', 
    'is_open', 
    'id', 
    'stats', 
    'title', 
    'announce_date', 
    'score', 
    'access_method', 
    'announcements', 
    'taxonomies', 
    'type', 
    'status', 
    'description', 
    'datetime_local', 
    'visible_until_utc', 
    'time_tbd', 'date_tbd', 
    'performers', 
    'url', 
    'created_at', 
    'popularity', 
    'venue', 
    'short_title', 
    'datetime_utc', 
    'datetime_tbd']